# Predix — Stacks testnet

[project]
name = "predix"
description = "Prediction market BTC price next minute"
authors = []

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
clarity_version = 2
epoch = "2.5"

[contracts.test-usdcx]
path = "contracts/test-usdcx.clar"
clarity_version = 2
epoch = "2.5"

[contracts.predixv2]
path = "contracts/predixv2.clar"
clarity_version = 3
epoch = "3.0"

[contracts.predixv2-gateway]
path = "contracts/predixv2-gateway.clar"
clarity_version = 3
epoch = "3.0"

[contracts.predixv5]
path = "contracts/predixv5.clar"
clarity_version = 3
epoch = "3.0"

[contracts.gatewayv4]
path = "contracts/gatewayv4.clar"
clarity_version = 3
epoch = "3.0"
